version: 0.2

phases:
  install:
    commands:
      # Navigate to the service folder and install dependencies
      - cd nodejs_service  # Adjust this path to your actual service folder
      - npm install  # Install dependencies in the correct directory

  build:
    commands:
      - docker build -t nodejs_service .

artifacts:
  files:
    - Dockerfile
    - app.js  # Replace with your service entry file
    - package.json  # Include this in artifacts to deploy or distribute
