version: 0.2

phases:
  install:
    commands:
      # Check the repository structure to ensure you are navigating to the correct directory
      - ls -l  # List files to confirm directory structure
      - cd nodejs_service  # Make sure the directory exists
      - npm install  # Install dependencies in the correct directory

  build:
    commands:
      - docker build -t nodejs_service .

artifacts:
  files:
    - Dockerfile
    - app.js  # Replace with your service entry file
    - package.json  # Include this in artifacts to deploy or distribute
