version: 0.2

phases:
  install:
    commands:
      - python3 --version    # Check Python versionssss
      - sudo apt-get update
      - sudo apt-get install python3-venv -y  # Ensure venv is installed
      - python3 -m venv venv  # Create a virtual environment
      - source venv/bin/activate  # Activate the virtual environment
      - pip install --no-cache-dir -r requirements.txt  # Install dependencies
  build:
    commands:
      - docker build -t flask_service .

artifacts:
  files:
    - Dockerfile
    - app.py
    - requirements.txt
